apiVersion: apps/v1
kind: Deployment
metadata:
  name: nn
spec:
  selector:
    matchLabels:
      name: hdfs-nn
      kerberosService: nn
  replicas: 1
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: nn
      labels:
        name: hdfs-nn
        kerberosService: nn
    spec:
      containers:
      - command:
        - /start-namenode.sh
        name: nn
        ports:
        - containerPort: 9000
        image: 567802622977.dkr.ecr.us-west-2.amazonaws.com/hdfs:0.0.4
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/keytabs
          name: nn-keytab
      restartPolicy: Always
      volumes:
      - name: nn-keytab
        persistentVolumeClaim:
          claimName: server-keytab
      - name: nn-hadoop
        persistentVolumeClaim:
          claimName: nn-hadoop
