apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-dn1
spec:
  selector:
    matchLabels:
      name: hdfs-dn1
      kerberosService: dn1
  replicas: 1
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: dn1
      labels:
        name: hdfs-dn1
        kerberosService: dn1
    spec:
      containers:
      - command:
        - /start-datanode.sh
        name: dn1
        image: 567802622977.dkr.ecr.us-west-2.amazonaws.com/hdfs:0.0.4
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/keytabs
          name: dn1-keytab
      restartPolicy: Always
      volumes:
      - name: dn1-keytab
        persistentVolumeClaim:
          claimName: server-keytab