apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerberos
spec:
  selector:
    matchLabels:
      name: hdfs-kerberos
      kerberosService: kerberos
  replicas: 1
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: kerberos
      labels:
        name: hdfs-kerberos
        kerberosService: kerberos
    spec:
      containers:
      - command:
        - /start-kdc.sh
        name: kerberos
        image: 567802622977.dkr.ecr.us-west-2.amazonaws.com/hdfs:0.0.4
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/keytabs
          name: kerb-keytab
      restartPolicy: Always
      volumes:
      - name: kerb-keytab
        persistentVolumeClaim:
          claimName: server-keytab