apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-data-populator
spec:
  selector:
    matchLabels:
      name: hdfs-data-populator
      kerberosService: data-populator
  replicas: 1
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: data-populator
      labels:
        name: hdfs-data-populator
        kerberosService: data-populator
    spec:
      containers:
      - command:
        - /populate-data.sh
        name: data-populator
        image: 567802622977.dkr.ecr.us-west-2.amazonaws.com/hdfs:0.0.5
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/keytabs
          name: data-populator-keytab
      restartPolicy: Always
      volumes:
      - name: data-populator-keytab
        persistentVolumeClaim:
          claimName: server-keytab